### PR TITLE
fix: added default-params-in-modal-stories

### PR DESCRIPTION
**Pull request by cmcWebCode40**
#175

## What kind of change does this PR introduce?

Bug fix,

## What is the current behavior?

Modal default params button text not set.

## What is the new behavior?
`{
.....
  onCancelText: 'Cancel',
  onConfirmText: 'Confirm',
.....
}`

Feel free to include screenshots if it includes visual changes.

### CODE REVIEW

**Comment by MildTomato** [comment]
@cmcWebCode40 thanks for the PR 👍 

I'm not sure this actually fixes the issue though.

I don't think we should manually add the labels into stories if they are just the same as the default because there's no visual check as to wether the default values are working, and what they are.

default params seem to work fine when using the components in an app, it just seems to be storybook doesn't display them.
It seems to only affect strings though which is weird.

**Comment by cmcWebCode40** [comment]
@MildTomato 
Thanks for the feedback regarding this fix, 
I was actually having some issues installing the application on my machine to get started (I will get a screenshot and update later),
I would suggest there's proper documentation on how to get started on the readme file, that would go a long way.
Thanks

**Comment by MildTomato** [comment]
thanks for the feedback 😄 @cmcWebCode40 

There's an [old dev markdown](https://github.com/supabase/ui/blob/develop/development.md) on running storybook locally but it might be a bit outdated.

**Comment by MildTomato** [comment]
I'm just closing this for now, but feel free to make changes
I still can't work out what is wrong, might just be a storybook bug.

**Pull request closed without merging**
