### PR TITLE
test: render tests for button component

### PR DESCRIPTION
**Pull request by harshcut**
**Description**

Add tests for `<Button />` component, with no production code changes.

**Changelog**

- [x] should render button correctly
- [x] should render different text
- [x] should ignore events when disabled
- [x] should ignore events when loading

**Additional**

image

### CODE REVIEW

**Comment by MildTomato** [comment]
lgtm 🔥

**Comment by harshcut** [comment]
Should i create snapshot tests for components that are developed? Also having a `__tests__` directory for each component would be a much better solution to isolate actual components from their tests. Let me know what you think.

**Comment by MildTomato** [comment]
I guess that's so we can have filenames inside the directory that don't need to have 'test' in them, for testMatch rules

https://stackoverflow.com/a/55551668

**Comment by harshcut** [comment]
Yes, but you can use `.test.js` as an extension for the files inside `__tests__` directory. This is how libraries recommend writing test. [Ant Design](https://github.com/ant-design/ant-design/tree/master/components/button) follows the same pattern.

**Pull request merged**
