### PR TITLE
fix: Modal css styling fixed. also adjusted colors slightly and layout.

### PR DESCRIPTION
**Pull request by MildTomato**
fixes Modal styling which was breaking

### CODE REVIEW

**Comment by kiwicopple** [comment]
I won't create an issue for this, but perhaps we should make the button margin the same on the sides as it is on top/bottom

image


The icon spacing looks a bit awkward too, but I don't really know how it could be improved ¯\_(ツ)_/¯

**Comment by MildTomato** [comment]
that icon position - thought i'd fixed that.

i think it might be subjective, but I'd prefer padding spacing on action footers to have the same x padding as the content above it - a better example would be the screenshot below with more text/content in it, as the examples above don't have much text in them.

Screenshot 2021-01-13 at 18 23 11

I will fix the icon, it shouldn't look like that.

**Comment by kiwicopple** [comment]
I think your screenshot is less obvious because the grey is so light you can barely see it. In our dark modals the buttons seem a bit awkwardly placed because our lighter grey sticks out a lot more.

I'm not a huge fan of the icon on the screenshot you've shared either if I'm honest - it pushes the text so awkwardly right, so nothing feels like it fits together. 

different spacing everywhere

image

**Pull request merged**
