### PR TITLE
Feat/InputTextArea copy

### PR DESCRIPTION
**Pull request by i-pip**
## What kind of change does this PR introduce?

feature - addresses #303 

## What is the new behavior?

Adds `copy` button to Input.TextArea  

## Additional context

Screenshot 2021-12-30 at 01 20 08

### CODE REVIEW

**Comment by MildTomato** [comment]
@i-pip just need to remove the breadcrumb changes

**Comment by i-pip** [comment]
> @i-pip just need to remove the breadcrumb changes

done, a little git cleaning up and the breadcrumb changes are gone 😋

**Comment by MildTomato** [comment]
@i-pip nice one!

**Comment by MildTomato** [comment]
I added support for `actions` and also added the error icon in.

Also tried to fix the padding issue with all the actions/buttons inside the text area.

small caveat though is the content of the textarea goes behind all of the actions/error icon.

Screenshot 2022-01-02 at 1 01 26 PM

**Pull request merged**
