### PR TITLE
Test/auth unit tests

### PR DESCRIPTION
**Pull request by maciekgrzybek**
@MildTomato  - as we spoke some time ago on Discord (sorry for being so late with this, but apparently moving to a different country can be more occupying than I thought :D), this PR introduces new tests for the Auth component. I've added MSW.js to create unit/integration tests, as similar as possible to the actual app behavior. There are still a few TODOS, but I think this is a good starter. Let me know if something doesn't make sense here, happy to discuss :)

### CODE REVIEW

**Comment by maciekgrzybek** [comment]
Any news on that? :)

**Comment by MildTomato** [comment]
Oh yea, looks good. I'll merge it in soon. 
I've been busy with the `alpha` branch, haven't had time to look at this yet.

**Comment by maciekgrzybek** [comment]
Hey @MildTomato is this still valid?

**Comment by MildTomato** [comment]
@maciekgrzybek i didn't merge it in since we were moving auth component somewhere new.
https://github.com/supabase-community/auth-ui

**Comment by MildTomato** [comment]
@maciekgrzybek could you move your PR over there? 🙏

**Comment by maciekgrzybek** [comment]
@MildTomato Sure thing, will do it this week :)

**Comment by MildTomato** [comment]
## Supabase UI is being deprecated. 

We are moving the components to the main mono repo at [github.com/supabase/supabase](github.com/supabase/supabase).

The auth component has been moved to it's own repo and package.
[github.com/supabase-community/auth-ui](github.com/supabase-community/auth-ui).
You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).

@maciekgrzybek would you be ok to move your unit test spike over there?

**Comment by MildTomato** [comment]
sorry, just realized you've already tried to move it over there 🙈

**Pull request closed without merging**
