### PR TITLE
feat(auth): hide password based authentication

### LINKED ISSUE #244: Allow Auth component to hide email auth
# Feature request

## Is your feature request related to a problem? Please describe.

https://github.com/supabase/supabase/discussions/2318

"Is it possible to disable the email/password log in boxes in the Supabase UI? I'm trying to only have a single OAuth login available, but can't find where I could disable the email/password"

## Describe the solution you'd like

Add a prop to disable/hide the email auth functionality.
May need to change how the layout looks for this to look ok.

## Additional context

As an added bonus, the email and 0auth could be split up as exportable components, so you could import just the functionality you need, minimising the footprint of the component. 
Maybe best as a future update.

### PR DESCRIPTION
**Pull request by harshcut**
**Description**

Add a `onlyThirdPartyProviders` prop to hide password based authentication method. Partially closes #244.

**Changelog**

- [x] add `onlyThirdPartyProviders` as an optional `boolean`
- [x] prop defaults to false

**Additional**

image

### CODE REVIEW

**Review by YashKandalkar — COMMENTED** [review]
Maybe add this as an example in Auth.stories.tsx too
Edit: just saw, we can see this in storybook controls nvm :P

**Comment by mstibbard** [comment]
Could we also make magic link a boolean prop?

**Review by MildTomato — APPROVED** [review]
Awesome

**Pull request merged**
