### PR TITLE
patch: Added Image component with basic functionalities

### PR DESCRIPTION
**Pull request by galanteria01**
## What kind of change does this PR introduce?

This PR adds a intial support for image component in Supabase-UI, It has little features like avatar and responsive

## What is the current behavior?

Haven't found any issue on StoryBook, Will work more over it and add more features

## What is the new behavior?

Image component functions well with avatar and normal type and  a special responsive functionality

## Additional context

I would be furthur working over this feature and implementing more usable props and features.
[Normal Image](https://i.imgur.com/sOg21Ag.png)
[Circle Image](https://i.imgur.com/4v5B1nH.png)

### CODE REVIEW

**Comment by MildTomato** [comment]
You may need to update `roll.config.js` to include an import for this new component

**Comment by galanteria01** [comment]
> hey @galanteria01 👋
> 
> Could consider expanding this as an 'Avatar' component like https://ant.design/components/avatar/
> 
> I didn't really spec including an Image component in this library as we use NextJS a lot, so we end up using [Next Image](https://nextjs.org/docs/api-reference/next/image) for images.
> Although we could get this more tightly integrated with Supabase storage later when we have CDN / Auto transformation / optimisation support, and the images can be transformed easily - load the correct image format, size etc based on browser.
> 
> btw - You may need to update `rollup.config.js` to include an import for this new component so it's included in the build 😄

Yes, prolly I'll extend this to a Avatar component . Thanks for your explanation sir. I'll be submitting modified patch with changes suggested.
Looking forward for more work on Supabase-UI.

**Comment by MildTomato** [comment]
@galanteria01 sounds awesome !

I always forget to add in the import to rollup 😂 
Once you update rollup.config.js, run `npm run build` and it should build fine without errors.

PR any improvements you see fit. 

An avatar component would be awesome, especially if it can handle groups of avatars overlapping and showing '+' if there's too many too show. We should probably also have a Popover component that could be imported into it as well to show extra details.

Screenshot 2021-05-31 at 11 42 43

**Comment by galanteria01** [comment]
@MildTomato 
Yes sir, I'd be adding initial support of it today and by tomorrow would finish multiple props of it to make it fully functional. Popup can be implemented onclick of that which could be added as <Avatar.Popup/> . I would consider your advice once I'm done with implementation. Thank you sir

**Comment by MildTomato** [comment]
We could just add in new component for it.

We can use 
https://radix-ui.com/primitives/docs/components/popover - for a popover triggered by a click
https://radix-ui.com/primitives/docs/components/hover-card - for a popover triggered by hover

I might just implement them as 1 component though called 'Popover', and you can choose wether its triggered on hover or click. I think they are separate radix primitives because the aria labels are quite different for each one.

I can add that today, and then you can import it into whatever component you are working on.

**Pull request merged**
