### PR TITLE
RFC Feature/form component

### PR DESCRIPTION
**Pull request by MildTomato**
initial Form component attempt

to do: 
- [x] validation, inc regex check of value
- [x] input `required` prop
- [x] show correct error messages for each component if validation fails
- [x] support for all Form Input types

with this component we should be able to make an AutoForm, which could auto populate a Form component

### CODE REVIEW

**Review by dragos199993 — COMMENTED** [review]
Hello, I have a question. Isn't react-hook-form a safer solution in this? It's relatively small, with a lot of nice features like preventing useless rerenders. https://react-hook-form.com/ 
Thanks!

**Comment by MildTomato** [comment]
@dragos199993 that's a great point!  I never really looked at this.

Just seen this as well - https://react-hook-form.com/get-started#IntegratingwithUIlibraries
we could base a Form component around using this Controller component which could be interesting.

I'll take a look. thanks @dragos199993 👍

**Comment by dragos199993** [comment]
Glad I can help. If you want, I would gladly help you with this one.

**Comment by MildTomato** [comment]
If we used react-hook-form, and integrated into the library, the design of the form component could be a bit like this 

```js
// import library
import { Form, Button, Input, Select } from "@supabase/ui";
// resolver stuff
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";

// validation schema
const schema = yup.object().shape({
  firstName: yup.string().required(),
  iceCreamType: required(),
});

selectOptions = [
  { value: "chocolate", label: "Chocolate" },
  { value: "strawberry", label: "Strawberry" },
  { value: "vanilla", label: "Vanilla" },
];

export default function FormExample() {
  return (
    <Form
      resolver={yupResolver(schema)}
      onSubmit={(values) => console.log(values)}
    >
      <Form.Controller
        name="firstName"
        defaultValue="Jonny"
        render={({ field }) => <input {...field} />}
      >
        <Input />
      </Form.Controller>

      <Form.Controller name="iceCreamType" control={control}>
        <Select>
          {selectOptions.map((option) => (
            <Select.Option value={option.value}>{option.label}</Select.Option>
          ))}
        </Select>
      </Form.Controller>
      <Button htmlType="submit">Submit form</Button>
    </Form>
  );
}


```

Obviously i haven't tried this yet, but the basic premise is..

We use the react-hook-form controller component as a Form.Controller subcomponent, and it would essentially do the same as in their [docs example](https://react-hook-form.com/get-started#IntegratingwithUIlibraries).
The parent Form component would use the useForm() and pass in the resolver (if there is one).

I think the main benefit of having this in the library though is all the error messages are handled for you. So if there is an error, we use Context.Provider to send the error message back down from the Form component to the right data input component.

really like the idea that anyone can bring their own schema validation from Yup, Zod , Superstruct or Joi as well and it seems like it would work fine.

**Comment by enochndika** [comment]
I think this is great but I have a question, the main purpose of **react-hook-form** is to minimize re-rendering, that's why it is better to use an uncontrolled component (**register**) to manage fields. The Controller component will be re-rendered so often.

**Comment by MildTomato** [comment]
Example of form component now using Formik hook

```js
export const InputLevelValidation = () => {
  function validateEmail(value: string) {
    console.log('validateEmail running')
    let error
    if (!value) {
      error = 'Required'
    } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(value)) {
      error = 'Invalid email address'
    }
    return error
  }

  return (
    <Form
      initialValues={{
        email: '',
        firstname: '',
      }}
      validateOnBlur
      onSubmit={(values: any, { setSubmitting }: any) => {
        setTimeout(() => {
          alert(JSON.stringify(values, null, 2))
          setSubmitting(false)
        }, 400)
      }}
    >
      {({ isSubmitting }: any) => (
        <div className="space-y-4">
          <Input
            id="email"
            label="email"
            placeholder="something in here"
            labelOptional="This is a required field"
            validation={validateEmail}
          />
          <Input
            id="firstname"
            label="firstname"
            placeholder="something in here"
          />
          <Button loading={isSubmitting} type="primary" htmlType="submit">
            Submit
          </Button>
        </div>
      )}
    </Form>
  )
}```

**Comment by MildTomato** [comment]
I'll merge this into the Beta branch for a beta release.

I'll also be adding in the theming changes into the beta branch as well later - although still need to play around with the set up a bit.

**Pull request merged**
