### PR TITLE
fix: persist form data when switching views

### PR DESCRIPTION
**Pull request by menor**
When switching between sign in and sign up any already entered data data is now persisted

Done by lifting the state getter and setters of the inputs fields one level up (to Auth) and passing it down as props to EmailAuth

Had to modify the Input component to take a default value, so we can have it prefilled, since we are mounting and unmounting it on view change.

### CODE REVIEW

**Comment by MildTomato** [comment]
thanks @menor for looking at this.

I've just tested this in storybook though and the forms are not usable.

It looks like whenever a new character is entered into either Email or Password Input, the component re renders and then the Input is no longer in focus.

**Comment by MildTomato** [comment]
If you can make the changes so the Inputs work OK and not lose focus then we can merge it in 😄 

I was testing it by just using the storybook preview. You can run it with `npm run storybook`

**Comment by menor** [comment]
Oops, I see what you mean 😬
Will try to fix that, sorry

**Comment by menor** [comment]
It seems to work now, let me know if you need any other change. Thanks for your patience.

**Comment by MildTomato** [comment]
@menor awesome, i'll take a look shortly!

**Comment by MildTomato** [comment]
@menor looks great 🔥 

i added some stronger types as the view change was just accepting any string.

merging it in :D

**Pull request merged**
