### PR TITLE
update @headlessui/react to latest 1.0.0

### PR DESCRIPTION
**Pull request by mudssrali**
## What kind of change does this PR introduce?

Updating `@headlessui/react` from `0.3.2` to `1.0.0`

### CODE REVIEW

**Comment by mudssrali** [comment]
@MildTomato you already did :p closing this PR

**Comment by MildTomato** [comment]
@mudssrali thanks anyway 🔥

**Comment by MildTomato** [comment]
@mudssrali btw, this change is in the latest release, which is just building now.

**Comment by mudssrali** [comment]
> @mudssrali btw, this change is in the latest release, which is just building now.

Yes, it's in latest release but I closely looked it's development, they shipped it after months

**Pull request closed without merging**
