### PR TITLE
fix: add in redirectTo prop for Auth component

### LINKED ISSUE #182: Support redirectTo for the Auth component
# Feature request
The [sign in](https://supabase.io/docs/reference/javascript/auth-signin#sign-in-with-redirect) supports **redirectTo**. However, the [Auth component](https://ui.supabase.io/components/auth) currently does not support that. It would be great if the Auth component supports that.

### PR DESCRIPTION
**Pull request by MildTomato**
• fixes #182

### CODE REVIEW

**Comment by MildTomato** [comment]
this needs testing

**Comment by MildTomato** [comment]
also need to add an apple icon for the apple social auth button

**Comment by Etheonor** [comment]
Can someone merge this one? It would be really useful!

**Pull request merged**
