### PR TITLE
fix: dropdown radio padding for item indicator

### PR DESCRIPTION
**Pull request by joshenlim**
## What kind of change does this PR introduce?

image

Ensure that dropdown radio items have consistent spacing (basically emulated how radix UI implemented it)

### CODE REVIEW

**Comment by MildTomato** [comment]
@joshenlim looks good

I think you might need to isolate the padding to just checkbox and radio items though

Screenshot 2021-05-28 at 09 38 56
Screenshot 2021-05-28 at 09 38 51

**Comment by joshenlim** [comment]
Ahh okay gotcha on this! Will push a fix today

**Comment by joshenlim** [comment]
just pushed a quick fix for this, also eyeballed the other dropdown components to make sure they look fine
quick question as well, how do i get my storybook styling to look like yours haha, the black background, font family etc

**Comment by MildTomato** [comment]
@joshenlim looks like something is wrong. lets screenshare later and debug

**Comment by MildTomato** [comment]
Looks related, got a similar screenshot here https://github.com/supabase/ui/pull/207

**Comment by MildTomato** [comment]
LGTM 🔥

**Comment by MildTomato** [comment]
@joshenlim ahhh

see this screenshot on this PR.
I think your using the wrong toggle for dark mode.
https://github.com/supabase/ui/pull/207#issuecomment-852287632

**Comment by joshenlim** [comment]
ahh gotcha on this ^ yeah i was using the sun/moon icon for the toggle, but oddly the font seems weird on my storybook - is there supposed to be a font loaded?

image

**Pull request merged**
