### PR TITLE
Avatar component clean up (Avatar Variant and AvatarGroup)

### PR DESCRIPTION
**Pull request by pknn**
## What kind of change does this PR introduce?

- Added variant usage for `Avatar` component
- Added `AvatarGroup`
- Clean up some code

## What is the current behavior?

- Variant prop on Avatar does nothing

## What is the new behavior?

- Variant prop on Avatar will do something
- AvatarGroup component

`circle` (default)

  Screen Shot 2564-10-23 at 20 33 53  

`square`

Screen Shot 2564-10-23 at 20 34 18

`AvatarGroup`
Horizontal
Screen Shot 2564-10-24 at 13 25 24
Vertical
Screen Shot 2564-10-24 at 13 25 38

## Additional context

__OPEN FOR SUGGESTION__

### CODE REVIEW

**Comment by pknn** [comment]
@MildTomato Is this PR any good? 😅

**Comment by MildTomato** [comment]
@pknn 

I think its a good start, it's probably best to look at this as a starting point and we keep improving it with more PRs.

I think it's probably good to look at it from how it would be used, how to use an image inside the component, and how to use an icon in it.

So with an image, maybe we can do this so someone can use whatever image markup they like.
probably very helpful for anyone using something like Next/Image or maybe things like Cloudinary SDK
```js
<Avatar src={<Img src="imgUrl"/>} size={"small"} type={"rounded"}/>
```

and maybe src can also take a string as well, in case they are not bothered about using their own img tag
```js
<Avatar src="imgUrl" size={"small"} type={"rounded"}/>
```

same for icon, just pass the icon through a prop
```js
<Avatar icon={<IconUser />} size={"small"} type={"square"}/>
```

**Comment by pknn** [comment]
@MildTomato I think what you proposed is pretty much what I would love to use. We can set it as a milestone for `Avatar` component, then iteratively working towards it.

**Comment by MildTomato** [comment]
### Supabase UI is being deprecated.

As part of that, we are closing Pull Requests in this repo for now.

If you'd like to still make these changes, you could consider making these changes in https://github.com/supabase/supabase/tree/master/packages/ui

---

We are moving the components to the main mono repo at [https://github.com/supabase/supabase](https://github.com/supabase/supabase).

The auth component has been moved to it's own repo and package. [https://github.com/supabase-community/auth-ui](https://github.com/supabase-community/auth-ui). You can also read the [docs for auth ui here](https://supabase.com/docs/guides/auth/auth-helpers/auth-ui).

**Pull request closed without merging**
